#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  ex-inventory-management-sandbox:
    image: digitalasset/ex-inventory-management-sandbox:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-sandbox
    ports:
      - "127.0.0.1:7600:7600"
  ex-inventory-management-navigator:
    image: digitalasset/ex-inventory-management-navigator:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-navigator
    depends_on:
      - "ex-inventory-management-sandbox"
    ports:
      - "127.0.0.1:7500:7500"
    environment:
      - SANDBOX_HOST=ex-inventory-management-sandbox
      - SANDBOX_PORT=7600
  ex-inventory-management-bitcoin:
      image: digitalasset/ex-inventory-management-bitcoin:0.0.1
      build:
        context: .
        dockerfile: Dockerfile-bitcoin
      ports:
        - "127.0.0.1:19091:19091"
  ex-inventory-management-bots:
    image: digitalasset/ex-inventory-management-bots:0.0.1
    build:
      context: .
      dockerfile: Dockerfile-bots
    depends_on:
      - "ex-inventory-management-sandbox"
      - "ex-inventory-management-bitcoin"
    environment:
      - SANDBOX_HOST=ex-inventory-management-sandbox
      - SANDBOX_PORT=7600
      - BITCOIN_HOST=ex-inventory-management-bitcoin
      - BITCOIN_PORT=19091
      - BITCOIN_USERNAME=admin1
      - BITCOIN_PASSWORD=123
